### ISSUE TITLE
Can't import modules

### ISSUE THREAD

**Issue by catty-dev** [MParvin/TR-CMD#4]
Traceback (most recent call last):
  File "/home/ubuntu/TR-CMD/bot.py", line 12, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters
  File "/usr/local/lib/python3.10/dist-packages/telegram/__init__.py", line 45, in <module>
    from .files.file import File
  File "/usr/local/lib/python3.10/dist-packages/telegram/files/file.py", line 22, in <module>
    from future.backports.urllib import parse as urllib_parse
  File "/usr/local/lib/python3.10/dist-packages/future/backports/__init__.py", line 17, in <module>
    from .misc import (ceil,
  File "/usr/local/lib/python3.10/dist-packages/future/backports/misc.py", line 19, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

I've installed all requirements

**Comment by MParvin** [comment]
Sorry for late answer :(
According to the following error,, here is  an issue for the "collection" module in python 3.10.
```
from collections import Mapping, MutableMapping
```

In python3.10 some part of the "collection" module have been moved to the 'collections.abc' module.

so, please use python3.9 or lower to fix this error.
